// 'https://ddragon.leagueoflegends.com/cdn/9.8.1/data/en_GB/champion.json'
const Champion =
{
	AATROX: {value: 266, label: 'Aatrox' },
	AHRI: {value: 103, label: 'Ahri' },
	AKALI: {value: 84, label: 'Akali' },
	ALISTAR: {value: 12, label: 'Alistar' },
	AMUMU: {value: 32, label: 'Amumu' },
	ANIVIA: {value: 34, label: 'Anivia' },
	ANNIE: {value: 1, label: 'Annie' },
	ASHE: {value: 22, label: 'Ashe' },
	AURELIONSOL: {value: 136, label: 'Aurelion Sol' },
	AZIR: {value: 268, label: 'Azir' },
	BARD: {value: 432, label: 'Bard' },
	BLITZCRANK: {value: 53, label: 'Blitzcrank' },
	BRAND: {value: 63, label: 'Brand' },
	BRAUM: {value: 201, label: 'Braum' },
	CAITLYN: {value: 51, label: 'Caitlyn' },
	CAMILLE: {value: 164, label: 'Camille' },
	CASSIOPEIA: {value: 69, label: 'Cassiopeia' },
	CHOGATH: {value: 31, label: 'Cho\'Gath' },
	CORKI: {value: 42, label: 'Corki' },
	DARIUS: {value: 122, label: 'Darius' },
	DIANA: {value: 131, label: 'Diana' },
	DRAVEN: {value: 119, label: 'Draven' },
	DRMUNDO: {value: 36, label: 'Dr. Mundo' },
	EKKO: {value: 245, label: 'Ekko' },
	ELISE: {value: 60, label: 'Elise' },
	EVELYNN: {value: 28, label: 'Evelynn' },
	EZREAL: {value: 81, label: 'Ezreal' },
	FIDDLESTICKS: {value: 9, label: 'Fiddlesticks' },
	FIORA: {value: 114, label: 'Fiora' },
	FIZZ: {value: 105, label: 'Fizz' },
	GALIO: {value: 3, label: 'Galio' },
	GANGPLANK: {value: 41, label: 'Gangplank' },
	GAREN: {value: 86, label: 'Garen' },
	GNAR: {value: 150, label: 'Gnar' },
	GRAGAS: {value: 79, label: 'Gragas' },
	GRAVES: {value: 104, label: 'Graves' },
	HECARIM: {value: 120, label: 'Hecarim' },
	HEIMERDINGER: {value: 74, label: 'Heimerdinger' },
	ILLAOI: {value: 420, label: 'Illaoi' },
	IRELIA: {value: 39, label: 'Irelia' },
	IVERN: {value: 427, label: 'Ivern' },
	JANNA: {value: 40, label: 'Janna' },
	JARVANIV: {value: 59, label: 'Jarvan IV' },
	JAX: {value: 24, label: 'Jax' },
	JAYCE: {value: 126, label: 'Jayce' },
	JHIN: {value: 202, label: 'Jhin' },
	JINX: {value: 222, label: 'Jinx' },
	KAISA: {value: 145, label: 'Kai\'Sa' },
	KALISTA: {value: 429, label: 'Kalista' },
	KARMA: {value: 43, label: 'Karma' },
	KARTHUS: {value: 30, label: 'Karthus' },
	KASSADIN: {value: 38, label: 'Kassadin' },
	KATARINA: {value: 55, label: 'Katarina' },
	KAYLE: {value: 10, label: 'Kayle' },
	KAYN: {value: 141, label: 'Kayn' },
	KENNEN: {value: 85, label: 'Kennen' },
	KHAZIX: {value: 121, label: 'Kha\'Zix' },
	KINDRED: {value: 203, label: 'Kindred' },
	KLED: {value: 240, label: 'Kled' },
	KOGMAW: {value: 96, label: 'Kog\'Maw' },
	LEBLANC: {value: 7, label: 'LeBlanc' },
	LEESIN: {value: 64, label: 'Lee Sin' },
	LEONA: {value: 89, label: 'Leona' },
	LISSANDRA: {value: 127, label: 'Lissandra' },
	LUCIAN: {value: 236, label: 'Lucian' },
	LULU: {value: 117, label: 'Lulu' },
	LUX: {value: 99, label: 'Lux' },
	MALPHITE: {value: 54, label: 'Malphite' },
	MALZAHAR: {value: 90, label: 'Malzahar' },
	MAOKAI: {value: 57, label: 'Maokai' },
	MASTERYI: {value: 11, label: 'Master Yi' },
	MISSFORTUNE: {value: 21, label: 'Miss Fortune' },
	MONKEYKING: {value: 62, label: 'Wukong' },
	MORDEKAISER: {value: 82, label: 'Mordekaiser' },
	MORGANA: {value: 25, label: 'Morgana' },
	NAMI: {value: 267, label: 'Nami' },
	NASUS: {value: 75, label: 'Nasus' },
	NAUTILUS: {value: 111, label: 'Nautilus' },
	NEEKO: {value: 518, label: 'Neeko' },
	NIDALEE: {value: 76, label: 'Nidalee' },
	NOCTURNE: {value: 56, label: 'Nocturne' },
	NUNU: {value: 20, label: 'Nunu & Willump' },
	OLAF: {value: 2, label: 'Olaf' },
	ORIANNA: {value: 61, label: 'Orianna' },
	ORNN: {value: 516, label: 'Ornn' },
	PANTHEON: {value: 80, label: 'Pantheon' },
	POPPY: {value: 78, label: 'Poppy' },
	PYKE: {value: 555, label: 'Pyke' },
	QUINN: {value: 133, label: 'Quinn' },
	RAKAN: {value: 497, label: 'Rakan' },
	RAMMUS: {value: 33, label: 'Rammus' },
	REKSAI: {value: 421, label: 'Rek\'Sai' },
	RENEKTON: {value: 58, label: 'Renekton' },
	RENGAR: {value: 107, label: 'Rengar' },
	RIVEN: {value: 92, label: 'Riven' },
	RUMBLE: {value: 68, label: 'Rumble' },
	RYZE: {value: 13, label: 'Ryze' },
	SEJUANI: {value: 113, label: 'Sejuani' },
	SHACO: {value: 35, label: 'Shaco' },
	SHEN: {value: 98, label: 'Shen' },
	SHYVANA: {value: 102, label: 'Shyvana' },
	SINGED: {value: 27, label: 'Singed' },
	SION: {value: 14, label: 'Sion' },
	SIVIR: {value: 15, label: 'Sivir' },
	SKARNER: {value: 72, label: 'Skarner' },
	SONA: {value: 37, label: 'Sona' },
	SORAKA: {value: 16, label: 'Soraka' },
	SWAIN: {value: 50, label: 'Swain' },
	SYLAS: {value: 517, label: 'Sylas' },
	SYNDRA: {value: 134, label: 'Syndra' },
	TAHMKENCH: {value: 223, label: 'Tahm Kench' },
	TALIYAH: {value: 163, label: 'Taliyah' },
	TALON: {value: 91, label: 'Talon' },
	TARIC: {value: 44, label: 'Taric' },
	TEEMO: {value: 17, label: 'Teemo' },
	THRESH: {value: 412, label: 'Thresh' },
	TRISTANA: {value: 18, label: 'Tristana' },
	TRUNDLE: {value: 48, label: 'Trundle' },
	TRYNDAMERE: {value: 23, label: 'Tryndamere' },
	TWISTEDFATE: {value: 4, label: 'Twisted Fate' },
	TWITCH: {value: 29, label: 'Twitch' },
	UDYR: {value: 77, label: 'Udyr' },
	URGOT: {value: 6, label: 'Urgot' },
	VARUS: {value: 110, label: 'Varus' },
	VAYNE: {value: 67, label: 'Vayne' },
	VEIGAR: {value: 45, label: 'Veigar' },
	VELKOZ: {value: 161, label: 'Vel\'Koz' },
	VI: {value: 254, label: 'Vi' },
	VIKTOR: {value: 112, label: 'Viktor' },
	VLADIMIR: {value: 8, label: 'Vladimir' },
	VOLIBEAR: {value: 106, label: 'Volibear' },
	WARWICK: {value: 19, label: 'Warwick' },
	XAYAH: {value: 498, label: 'Xayah' },
	XERATH: {value: 101, label: 'Xerath' },
	XINZHAO: {value: 5, label: 'Xin Zhao' },
	YASUO: {value: 157, label: 'Yasuo' },
	YORICK: {value: 83, label: 'Yorick' },
	ZAC: {value: 154, label: 'Zac' },
	ZED: {value: 238, label: 'Zed' },
	ZIGGS: {value: 115, label: 'Ziggs' },
	ZILEAN: {value: 26, label: 'Zilean' },
	ZOE: {value: 142, label: 'Zoe' },
	ZYRA: {value: 143, label: 'Zyra' },
	
	findById(id)
	{
		return Object.values(this).find(champ => {return champ.value === id})
	}
}

module.exports = Champion;